<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
<parent>
    <groupId>com.github.knextsunj.categorymanagement</groupId>
    <artifactId>category-management-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
</parent>
    <artifactId>category-management-framework</artifactId>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <log4j2.version>2.17.2</log4j2.version>
        <jakarta.ee.version>10.0.0</jakarta.ee.version>
        <org.microprofile.version>7.0</org.microprofile.version>
        <jackson.version>2.15.2</jackson.version>
        <jakarta.ee.version>10.0.0</jakarta.ee.version>
    </properties>

    <dependencies>
<!--        <dependency>-->
<!--            <groupId>jakarta.platform</groupId>-->
<!--            <artifactId>jakarta.jakartaee-api</artifactId>-->
<!--            <version>${jakarta.ee.version}</version>-->
<!--            <scope>provided</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.microprofile</groupId>-->
<!--            <artifactId>microprofile</artifactId>-->
<!--            <version>${org.microprofile.version}</version>-->
<!--            <type>pom</type>-->
<!--            <scope>provided</scope>-->
<!--        </dependency>-->
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>${jakarta.ee.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.knextsunj.categorymanagement</groupId>
            <artifactId>category-management-application</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.github.knextsunj.categorymanagement</groupId>
            <artifactId>category-management-coredomain</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-base</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jaxb-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-parameter-names</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>

    </dependencies>

<!--    <build>-->
<!--        <finalName>category-management-framework</finalName>-->
<!--        <pluginManagement>-->
<!--            <plugins>-->
<!--                <plugin>-->
<!--                    <groupId>org.apache.maven.plugins</groupId>-->
<!--                    <artifactId>maven-war-plugin</artifactId>-->
<!--                    <version>3.3.2</version>-->
<!--                </plugin>-->
<!--                <plugin>-->
<!--                    <groupId>io.openliberty.tools</groupId>-->
<!--                    <artifactId>liberty-maven-plugin</artifactId>-->
<!--                    <version>3.11.2</version>-->
<!--                </plugin>-->
<!--            </plugins>-->
<!--        </pluginManagement>-->
<!--        <plugins>-->
<!--            <plugin>-->
<!--                <groupId>io.openliberty.tools</groupId>-->
<!--                <artifactId>liberty-maven-plugin</artifactId>-->
<!--            </plugin>-->
<!--        </plugins>-->
<!--    </build>-->
</project>
